# Generated by Django 5.0.1 on 2024-02-24 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_number', models.CharField(max_length=50, verbose_name='Номер реагента')),
                ('reagent_name', models.CharField(max_length=100, verbose_name='Наименование реагента')),
                ('container_number', models.CharField(max_length=50, verbose_name='Номер контейнера')),
                ('quantity', models.IntegerField(verbose_name='Количество реагента')),
                ('reagent_type', models.CharField(max_length=50, verbose_name='Тип реагента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('storage_temperature', models.IntegerField(verbose_name='Температура хранения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('special_instructions', models.TextField(verbose_name='Особые указания')),
                ('last_usage', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Последний пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
