# Generated by Django 5.0.1 on 2024-02-24 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_reagent_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код типа')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование типа')),
            ],
        ),
        migrations.CreateModel(
            name='OtherSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_concentration', models.FloatField(verbose_name='Концентрация составляющих веществ')),
                ('molarity', models.FloatField(verbose_name='Молярность раствора')),
                ('ph', models.FloatField(verbose_name='Х раствора')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagent', verbose_name='Код реагента')),
                ('reagent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagenttype', verbose_name='Код типа')),
            ],
        ),
        migrations.AlterField(
            model_name='reagent',
            name='reagent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagenttype', verbose_name='Тип реагента'),
        ),
    ]
