# Generated by Django 5.0.1 on 2024-02-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_buffersolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrySubstanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100, verbose_name='Поставщик')),
                ('purity', models.FloatField(verbose_name='Чистота')),
                ('applications', models.TextField(verbose_name='Допустимые применения')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagent', verbose_name='Код реагента')),
                ('reagent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagenttype', verbose_name='Код типа')),
            ],
        ),
        migrations.CreateModel(
            name='FermentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='Класс фермента')),
                ('activity_per_ml', models.FloatField(verbose_name='Ед активности / мл')),
                ('optimal_temperature', models.IntegerField(verbose_name='Оптимальная температура')),
                ('deactivation_capability', models.CharField(max_length=100, verbose_name='Возможность дезактивации')),
                ('storage_buffer_type', models.CharField(max_length=100, verbose_name='Тип буфера хранения')),
                ('reaction_buffer', models.CharField(max_length=100, verbose_name='Реакционный буфер')),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagent', verbose_name='Код реагента')),
                ('reagent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagenttype', verbose_name='Код типа')),
            ],
        ),
        migrations.CreateModel(
            name='PrimerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(verbose_name='Последовательность')),
                ('annealing_temperature', models.IntegerField(verbose_name='Температура отжига')),
                ('composition_for_annealing_temperature', models.CharField(max_length=100, verbose_name='Состав смеси для температуры отжига')),
                ('concentration', models.FloatField(verbose_name='Концентрация')),
                ('length', models.IntegerField(verbose_name='Длина праймера')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagent', verbose_name='Код реагента')),
                ('reagent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagenttype', verbose_name='Код типа')),
            ],
        ),
        migrations.CreateModel(
            name='RestrictionEnzymeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_percentage_in_buffers', models.FloatField(verbose_name='% активности в буферах')),
                ('activity_per_ml', models.FloatField(verbose_name='Ед активности / мл')),
                ('optimal_temperature', models.IntegerField(verbose_name='Оптимальная температура')),
                ('deactivation_capability', models.CharField(max_length=100, verbose_name='Возможность дезактивации')),
                ('storage_buffer_type', models.CharField(max_length=100, verbose_name='Тип буфера хранения')),
                ('reaction_buffer', models.CharField(max_length=100, verbose_name='Реакционный буфер')),
                ('restriction_site', models.CharField(max_length=100, verbose_name='Сайт рестрикции')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagent', verbose_name='Код реагента')),
                ('reagent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagenttype', verbose_name='Код типа')),
            ],
        ),
        migrations.CreateModel(
            name='SubstanceSolutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_reagent', models.CharField(max_length=100, verbose_name='Сухой реагент')),
                ('dry_reagent_quantity', models.FloatField(verbose_name='Количество сухого реагента')),
                ('concentration', models.FloatField(verbose_name='Концентрация')),
                ('solvent', models.CharField(max_length=100, verbose_name='Растворитель')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagent', verbose_name='Код реагента')),
                ('reagent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reagenttype', verbose_name='Код типа')),
            ],
        ),
    ]
