# Generated by Django 5.0.1 on 2024-02-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_container_container_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='reagent_number',
        ),
    ]
