# Generated by Django 5.0.1 on 2024-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_container_reagent_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_number',
            field=models.CharField(max_length=50, verbose_name='Номер контейнера'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='reagent_number',
            field=models.IntegerField(verbose_name='Номер реагента'),
        ),
    ]
